import type {Metadata} from "next";
import {Montserrat, Open_Sans} from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar";
import Banner from "@/components/Banner";

const montserrat = Montserrat({
	subsets: ['latin'],     // Assurez-vous de spécifier "latin" (ou autre si nécessaire)
	variable: '--font-montserrat',
});
const open_sans = Open_Sans({
	subsets: ['latin'],     // Assurez-vous de spécifier "latin" (ou autre si nécessaire)
	variable: '--font-open-sans',
});

export const metadata: Metadata = {
	title: "Create Next App",
	description: "Generated by create next app",
};

export default function RootLayout({children}: Readonly<{ children: React.ReactNode }>) {

	const firstVisit = true;

	return (
		<html lang="fr" className={`${montserrat.variable} ${open_sans.variable} antialiased`}>
		<body>
		{firstVisit && <Banner/>}
		<div className="max-w-[85vw] mx-auto font-[open-sans]">
			<Navbar/>
			{children}
		</div>

		</body>
		</html>
	);
}
